<?php

return [
'/services/depannage-volets-charnoz-sur-ain' => '/services/depannage-volets-roulants-charnoz-sur-ain',
'/services/pose-volets-la-balme-les-grottes' => '/services/pose-volets-roulants-la-balme-les-grottes',
'/services/pose-portes-charnoz-sur-ain' => '/services/pose-portes-entree-charnoz-sur-ain',
'/services/pose-portes-tramoyes' => '/services/pose-portes-entree-tramoyes',
'/services/depannage-volets-loyettes' => '/services/depannage-volets-roulants-loyettes',
'/services/depannage-volets-lagnieu' => '/services/depannage-volets-roulants-lagnieu',
'/services/pose-porte-entree-la-balme-les-grottes' => '/services/pose-portes-entree-la-balme-les-grottes',
'/services/pose-portes-villars-les-dombes' => '/services/pose-portes-entree-villars-les-dombes',
'/services/depannage-volets-perouges' => '/services/depannage-volets-roulants-perouges',
'/services/pose-porte-entree-beynost' => '/services/pose-portes-entree-beynost',
'/services/pose-porte-entree-meximieux' => '/services/pose-portes-entree-meximieux',
'/services/pose-porte-entree-saint-andre-de-corcy' => '/services/pose-portes-entree-saint-andre-de-corcy',
'/services/pose-volets-saint-vulbas' => '/services/pose-volets-roulants-saint-vulbas',
'/services/pose-volets-sainte-julie' => '/services/pose-volets-roulants-sainte-julie',
'/services/pose-porte-entree-chazey-sur-ain' => '/services/pose-portes-entree-chazey-sur-ain',
'/services/pose-porte-entree-montluel' => '/services/pose-portes-entree-montluel',
'/services/pose-portes-saint-vulbas' => '/services/pose-portes-entree-saint-vulbas',
'/services/depannage-volets-saint-andre-de-corcy' => '/services/depannage-volets-roulants-saint-andre-de-corcy',
'/services/pose-porte-entree-dagneux' => '/services/pose-portes-entree-dagneux',
'/services/pose-porte-entree-perouges' => '/services/pose-portes-entree-perouges',
'/services/pose-portes-meximieux' => '/services/pose-portes-entree-meximieux',
'/services/pose-porte-entree-sainte-julie' => '/services/pose-portes-entree-sainte-julie',
'/services/pose-volets-tramoyes' => '/services/pose-volets-roulants-tramoyes',
'/services/pose-porte-entree-saint-vulbas' => '/services/pose-portes-entree-saint-vulbas',
'/services/pose-porte-entree-miribel' => '/services/pose-portes-entree-miribel',
'/services/pose-porte-entree-lagnieu' => '/services/pose-portes-entree-lagnieu',
'/services/pose-porte-entree-charnoz-sur-ain' => '/services/pose-portes-entree-charnoz-sur-ain',
'/services/pose-porte-entree-villars-les-dombes' => '/services/pose-portes-entree-villars-les-dombes',
'/services/pose-porte-entree-leyment' => '/services/pose-portes-entree-leyment',
'/services/pose-porte-entree-villieu-loyes-mollon' => '/services/pose-portes-entree-villieu-loyes-mollon',
'/services/pose-porte-entree-amberieu-en-bugey' => '/services/pose-portes-entree-amberieu-en-bugey',
'/services/pose-porte-entree-loyettes' => '/services/pose-portes-entree-loyettes',
'/services/pose-porte-entree-tramoyes' => '/services/pose-portes-entree-tramoyes',
'/qui-suis-je-' => '/presentation-jdtravauxservices',
'/mes-services' => '/services',
];
